# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poke_count',
            field=models.TextField(default=0),
        ),
    ]
