# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_user_poke_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='poke_count',
            field=models.IntegerField(default=0),
        ),
    ]
